### ISSUE TITLE
Yocto Warrior changes

### ISSUE THREAD

**Issue by paroque28** [rdanter/wrl-rpi-bsp#1]
From release notes:
 - arch-armv8a.inc: add tune include for armv8

rpi3-64.conf:8 needs to be updated in order to fix the following error:

wrl-rpi-bsp/conf/machine/rpi3-64.conf:8: Could not include required file conf/machine/include/arm/arch-armv8.inc

It worked when I changed  arch-armv8.inc to arch-armv8a.inc

**Comment by rdanter** [comment]
Thanks, I will take a look. Is this only since RCPL 6? I have not had time to test that yet.

**Comment by rdanter** [comment]
> It worked when I changed arch-armv8.inc to arch-armv8a.inc

I have done a build here with LTS-18 RCPL 6 and did not encounter any issues. Also did a quick search for the inc file and did not fine the one for armv8a:

```
$ find . -name 'arch-armv8*\.inc'
./oe-core/meta/conf/machine/include/arm/arch-armv8.inc
```
So I wonder if you are using a different version? Can you tell me how to reproduce your issue?

Thanks
Rich

**Comment by rdanter** [comment]
Aha! I see, you are using the latest Yocto. This BSP is for WR Linux LTS which is still on Thud.
I have been thinking of creating a branch for the CI version, which I guess is now based on Warrior, but not had any time yet. The kernel is also newer, so I expect other changes will be needed too.

**Comment by paroque28** [comment]
Hi Richard, I am using the lastest version from open source.

## Install Wind River Linux LTS
```bash
mkdir my-project
cd my-project
git clone --branch master-wr https://github.com/WindRiver-OpenSourceLabs/wrlinux-x wrlinux-x
```
## Configure Wind River Linux LTS
```bash
./wrlinux-x/setup.sh --distro wrlinux --dl-layers --accept-eula yes
```
## Install RaspberryPi layer
```bash
cd  layers
git clone https://github.com/rdanter/wrl-rpi-bsp.git
```
Edit file `wrl-rpi-bsp/conf/layer.conf` and add warrior compatility as follows
```conf
 LAYERSERIES_COMPAT_rpi = "thud warrior"
```
add layer:
```bash
cd ..
. ./oe-init-build-env
bitbake-layers add-layer ../layers/wrl-rpi-bsp/
echo "MACHINE = \"rpi3-64\"" >> conf/local.conf
```
## Enable network connectivity
Change the conf/local.conf file and update
` BB_NO_NETWORK ?= '0'`
## Build Wind River Linux LTS
```bash
bitbake wrlinux-image-glibc-std
```

**Comment by paroque28** [comment]
Do you know how to clone WRLinux with thud instead of warrior?

**Comment by rdanter** [comment]
You can get the WR Linux 18 Base version, which ic based on thud, here: https://github.com/WindRiver-Labs/wrlinux-x

To build you will need to do something like this...
```
$ mkdir my-project
$ cd my-project
$ git clone --branch WRLINUX_10_18_BASE https://github.com/WindRiver-Labs/wrlinux-x
$ ./wrlinux-x/setup.sh --distro wrlinux --dl-layers
$ . environment-setup-x86_64-wrlinuxsdk-linux
$ . oe-init-build-env
$ bitbake-layers add-layer /path/to/wrl-rpi-bsp
$ echo "MACHINE = \"rpi3-64\"" >> conf/local.conf
$ echo "BB_NO_NETWORK = \"0\"" >> conf/local.conf
$ bitbake wrlinux-image-glibc-std
```
I have done a build here and encountered no problems except the expected CONFIG_ warnings from the kernel. Unfortunately I didn't have time to boot it though, please let me know how you get along.

**Comment by rdanter** [comment]
I have updated to Zeus with the latest patches, skipping Warrior.
